
const vanilla_template = () => ({
	"view_count":0,
	"version":19,
	"user_liked":false,
	"updated_at":"2018-02-28T16:47:53.294831",
	"title":null,
	"template":"parcel",
	"tags":[
	],
	"source_id":"vanilla",
	"privacy":0,
	"owned":false,
	"original_git_commit_sha":null,
	"original_git":null,
	"npm_dependencies":{
	"react-dom":"16.0.0",
	"react":"16.0.0"
	},
	"modules":[
		{
		"title":"index.html",
		"source_id":"vanilla",
		"shortid":"MWN4P",
		"is_binary":false,
		"id":"MWN4P",
		"directory_shortid":null,
		"code":"<html>\n\n<head>\n\t<title>Parcel Sandbox</title>\n\t<meta charset=\"UTF-8\" />\n</head>\n\n<body>\n\t<div id=\"app\"></div>\n\n\t<script src=\"src/index.js\"></script>\n</body>\n\n</html>"
		},
		{
		"title":"index.js",
		"source_id":"vanilla",
		"shortid":"wRo98",
		"is_binary":false,
		"id":"wRo98",
		"directory_shortid":"GXOoy",
		"code":"document.getElementById(\"app\").innerHTML = `\n<h1>Hello Parcel!</h1>\n<div>\n Look\n <a href=\"https://parceljs.org\" target=\"_blank\" rel=\"noopener noreferrer\">here</a>\n for more info about Parcel.\n</div>\n`;\n"
		},
		{
		"title":"package.json",
		"source_id":"vanilla",
		"shortid":"ZGQK6",
		"is_binary":false,
		"id":"ZGQK6",
		"directory_shortid":null,
		"code":"{\n \"name\": \"parcel-sandbox\",\n \"version\": \"1.0.0\",\n \"description\": \"Simple Parcel Sandbox\",\n \"main\": \"index.html\",\n \"scripts\": {\n \"start\": \"parcel index.html --open\",\n \"build\": \"parcel build index.html\"\n },\n \"dependencies\": {},\n \"devDependencies\": {\n \"parcel-bundler\": \"^1.6.1\"\n }\n}\n"
		}
	],
	"like_count":8,
	"id":"vanilla",
	"git":null,
	"forked_from_sandbox":null,
	"fork_count":0,
	"external_resources":[
	],
	"entry":"src/index.js",
	"directories":[
		{
		"title":"src",
		"source_id":"vanilla",
		"shortid":"GXOoy",
		"id":"GXOoy",
		"directory_shortid":null
		}
	],
	"description":null,
	"author":null
})

const create_react_app_template = (sandboxId, publicDirId, srcDirId, moduleIdArr) => (
	{
	npm_dependencies: {
		"react-dom": "16.0.0",
		"react": "16.0.0"
	},
	modules: [
         {
            "title":"package.json",
            "source_id":sandboxId,
            "shortid":moduleIdArr[0],
            "is_binary":false,
            "id":moduleIdArr[0],
            "directory_shortid":null,
            "code":"{\n  \"name\": \"new\",\n  \"version\": \"1.0.0\",\n  \"description\": \"\",\n  \"keywords\": [],\n  \"homepage\": \"https://codesandbox.io/s/new\",\n  \"main\": \"src/index.js\",\n  \"dependencies\": {\n    \"react\": \"16.2.0\",\n    \"react-dom\": \"16.2.0\",\n    \"react-scripts\": \"1.1.0\"\n  },\n  \"devDependencies\": {},\n  \"scripts\": {\n    \"start\": \"react-scripts start\",\n    \"build\": \"react-scripts build\",\n    \"test\": \"react-scripts test --env=jsdom\",\n    \"eject\": \"react-scripts eject\"\n  }\n}\n"
         },
         {
            "title":"index.html",
            "source_id":sandboxId,
            "shortid":moduleIdArr[1],
            "is_binary":false,
            "id":moduleIdArr[1],
            "directory_shortid":publicDirId,
            "code":"<!DOCTYPE html>\n<html lang=\"en\">\n\n<head>\n\t<meta charset=\"utf-8\">\n\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\n\t<meta name=\"theme-color\" content=\"#000000\">\n\t<!--\n      manifest.json provides metadata used when your web app is added to the\n      homescreen on Android. See https://developers.google.com/web/fundamentals/engage-and-retain/web-app-manifest/\n    -->\n\t<link rel=\"manifest\" href=\"%PUBLIC_URL%/manifest.json\">\n\t<link rel=\"shortcut icon\" href=\"%PUBLIC_URL%/favicon.ico\">\n\t<!--\n      Notice the use of %PUBLIC_URL% in the tags above.\n      It will be replaced with the URL of the `public` folder during the build.\n      Only files inside the `public` folder can be referenced from the HTML.\n\n      Unlike \"/favicon.ico\" or \"favicon.ico\", \"%PUBLIC_URL%/favicon.ico\" will\n      work correctly both with client-side routing and a non-root public URL.\n      Learn how to configure a non-root public URL by running `npm run build`.\n    -->\n\t<title>React App</title>\n</head>\n\n<body>\n\t<noscript>\n\t\tYou need to enable JavaScript to run this app.\n\t</noscript>\n\t<div id=\"root\"></div>\n\t<!--\n      This HTML file is a template.\n      If you open it directly in the browser, you will see an empty page.\n\n      You can add webfonts, meta tags, or analytics to this file.\n      The build step will place the bundled scripts into the <body> tag.\n\n      To begin the development, run `npm start` or `yarn start`.\n      To create a production bundle, use `npm run build` or `yarn build`.\n    -->\n</body>\n\n</html>"
         },
         {
            "title":"index.js",
            "source_id":sandboxId,
            "shortid":moduleIdArr[2],
            "is_binary":false,
            "id":moduleIdArr[2],
            "directory_shortid":srcDirId,
            "code":"//hey\nimport React from 'react';\nimport { render } from 'react-dom';\nimport Hello from './Hello';\n\nconst styles = {\n  fontFamily: 'sans-serif',\n  textAlign: 'center',\n};\n\nconst App = () => (\n  <div style={styles}>\n    <Hello name=\"CodeSandbox\" />\n    <h2>Start editing to see some magic happen {'\\u2728'}</h2>\n  </div>\n);\n\nrender(<App />, document.getElementById('root'));\n"
         },
         {
            "title":"Hello.js",
            "source_id":sandboxId,
            "shortid":moduleIdArr[3],
            "is_binary":false,
            "id":moduleIdArr[3],
            "directory_shortid":srcDirId,
            "code":"//this is working?\nimport React from 'react';\n\nexport default ({ name }) => <h1>Hello {name}!</h1>;\n"
         }
	],
	"entry":"src/index.js",
	"directories":[														//directories in sandbox
         {
            "title":"src",
            "source_id":sandboxId,
            "shortid":srcDirId,
            "id":srcDirId,
            "directory_shortid":null
         },
         {
            "title":"public",
            "source_id":sandboxId,
            "shortid":publicDirId,
            "id":publicDirId,
            "directory_shortid":null
         },
      ],
})

const vue_template = () => ({
	"view_count":0,
	"version":1,
	"user_liked":false,
	"updated_at":"2018-02-14T14:46:22.188786",
	"title":"Vue Template",
	"template":"vue-cli",
	"tags":[
	],
	"source_id":"vue",
	"privacy":0,
	"owned":false,
	"original_git_commit_sha":null,
	"original_git":null,
	"npm_dependencies":{
	"vue-router":"3.0.1",
	"vue":"2.5.2"
	},
	"modules":[
		{
		"title":"logo.png",
		"source_id":"vue",
		"shortid":"JQvBK",
		"is_binary":true,
		"id":"JQvBK",
		"directory_shortid":"0pn4G",
		"code":"https://upload.wikimedia.org/wikipedia/commons/f/f1/Vue.png"
		},
		{
		"title":"index.html",
		"source_id":"vue",
		"shortid":"BA1N",
		"is_binary":false,
		"id":"BA1N",
		"directory_shortid":null,
		"code":"<!DOCTYPE html>\n<html>\n\n<head>\n\t<meta charset=\"utf-8\">\n\t<meta name=\"viewport\" content=\"width=device-width,initial-scale=1.0\">\n\t<title>CodeSandbox Vue</title>\n</head>\n\n<body>\n\t<div id=\"app\"></div>\n\t<!-- built files will be auto injected -->\n</body>\n\n</html>"
		},
		{
		"title":"App.vue",
		"source_id":"vue",
		"shortid":"Wmo6v",
		"is_binary":false,
		"id":"Wmo6v",
		"directory_shortid":"VvnjX",
		"code":"<template>\n <div id=\"app\">\n <img width=\"25%\" src=\"./assets/logo.png\">\n <HelloWorld/>\n </div>\n</template>\n\n<script>\nimport HelloWorld from \"./components/HelloWorld\";\n\nexport default {\n name: \"App\",\n components: {\n HelloWorld\n }\n};\n</script>\n\n<style>\n#app {\n font-family: \"Avenir\", Helvetica, Arial, sans-serif;\n -webkit-font-smoothing: antialiased;\n -moz-osx-font-smoothing: grayscale;\n text-align: center;\n color: #2c3e50;\n margin-top: 60px;\n}\n</style>\n"
		},
		{
		"title":"main.js",
		"source_id":"vue",
		"shortid":"5RWAR",
		"is_binary":false,
		"id":"5RWAR",
		"directory_shortid":"VvnjX",
		"code":"// The Vue build version to load with the `import` command\n// (runtime-only or standalone) has been set in webpack.base.conf with an alias.\nimport Vue from \"vue\";\nimport App from \"./App\";\n\nVue.config.productionTip = false;\n\n/* eslint-disable no-new */\nnew Vue({\n el: \"#app\",\n components: { App },\n template: \"<App/>\"\n});\n"
		},
		{
		"title":".keep",
		"source_id":"vue",
		"shortid":"7kABG",
		"is_binary":false,
		"id":"7kABG",
		"directory_shortid":"ANqNP",
		"code":null
		},
		{
		"title":"package.json",
		"source_id":"vue",
		"shortid":"mEnXA",
		"is_binary":false,
		"id":"mEnXA",
		"directory_shortid":null,
		"code":"{\n \"name\": \"test-project\",\n \"version\": \"1.0.0\",\n \"description\": \"A Vue.js project\",\n \"main\": \"src/main.js\",\n \"private\": true,\n \"scripts\": {\n \"dev\": \"webpack-dev-server --inline --progress --config build/webpack.dev.conf.js\",\n \"start\": \"npm run dev\",\n \"unit\": \"jest --config test/unit/jest.conf.js --coverage\",\n \"test\": \"npm run unit\",\n \"lint\": \"eslint --ext .js,.vue src test/unit\",\n \"build\": \"node build/build.js\"\n },\n \"dependencies\": {\n \"vue\": \"^2.5.2\"\n },\n \"devDependencies\": {\n \"autoprefixer\": \"^7.1.2\",\n \"babel-core\": \"^6.22.1\",\n \"babel-eslint\": \"^8.2.1\",\n \"babel-helper-vue-jsx-merge-props\": \"^2.0.3\",\n \"babel-jest\": \"^21.0.2\",\n \"babel-loader\": \"^7.1.1\",\n \"babel-plugin-dynamic-import-node\": \"^1.2.0\",\n \"babel-plugin-syntax-jsx\": \"^6.18.0\",\n \"babel-plugin-transform-es2015-modules-commonjs\": \"^6.26.0\",\n \"babel-plugin-transform-runtime\": \"^6.22.0\",\n \"babel-plugin-transform-vue-jsx\": \"^3.5.0\",\n \"babel-preset-env\": \"^1.3.2\",\n \"babel-preset-stage-2\": \"^6.22.0\",\n \"chalk\": \"^2.0.1\",\n \"copy-webpack-plugin\": \"^4.0.1\",\n \"css-loader\": \"^0.28.0\",\n \"eslint\": \"^4.15.0\",\n \"eslint-config-airbnb-base\": \"^11.3.0\",\n \"eslint-friendly-formatter\": \"^3.0.0\",\n \"eslint-import-resolver-webpack\": \"^0.8.3\",\n \"eslint-loader\": \"^1.7.1\",\n \"eslint-plugin-import\": \"^2.7.0\",\n \"eslint-plugin-vue\": \"^4.0.0\",\n \"extract-text-webpack-plugin\": \"^3.0.0\",\n \"file-loader\": \"^1.1.4\",\n \"friendly-errors-webpack-plugin\": \"^1.6.1\",\n \"html-webpack-plugin\": \"^2.30.1\",\n \"jest\": \"^22.0.4\",\n \"jest-serializer-vue\": \"^0.3.0\",\n \"node-notifier\": \"^5.1.2\",\n \"optimize-css-assets-webpack-plugin\": \"^3.2.0\",\n \"ora\": \"^1.2.0\",\n \"portfinder\": \"^1.0.13\",\n \"postcss-import\": \"^11.0.0\",\n \"postcss-loader\": \"^2.0.8\",\n \"postcss-url\": \"^7.2.1\",\n \"rimraf\": \"^2.6.0\",\n \"semver\": \"^5.3.0\",\n \"shelljs\": \"^0.7.6\",\n \"uglifyjs-webpack-plugin\": \"^1.1.1\",\n \"url-loader\": \"^0.5.8\",\n \"vue-jest\": \"^1.0.2\",\n \"vue-loader\": \"^13.3.0\",\n \"vue-style-loader\": \"^3.0.1\",\n \"vue-template-compiler\": \"^2.5.2\",\n \"webpack\": \"^3.6.0\",\n \"webpack-bundle-analyzer\": \"^2.9.0\",\n \"webpack-dev-server\": \"^2.9.1\",\n \"webpack-merge\": \"^4.1.0\"\n },\n \"engines\": {\n \"node\": \">= 6.0.0\",\n \"npm\": \">= 3.0.0\"\n },\n \"browserslist\": [\n \"> 1%\",\n \"last 2 versions\",\n \"not ie <= 8\"\n ]\n}"
		},
		{
		"title":"HelloWorld.vue",
		"source_id":"vue",
		"shortid":"XXPGW",
		"is_binary":false,
		"id":"XXPGW",
		"directory_shortid":"JEP5J",
		"code":"<template>\n <div class=\"hello\">\n <h1>{{ msg }}</h1>\n <h2>Essential Links</h2>\n <ul>\n <li>\n <a\n href=\"https://vuejs.org\"\n target=\"_blank\"\n >\n Core Docs\n </a>\n </li>\n <li>\n <a\n href=\"https://forum.vuejs.org\"\n target=\"_blank\"\n >\n Forum\n </a>\n </li>\n <li>\n <a\n href=\"https://chat.vuejs.org\"\n target=\"_blank\"\n >\n Community Chat\n </a>\n </li>\n <li>\n <a\n href=\"https://twitter.com/vuejs\"\n target=\"_blank\"\n >\n Twitter\n </a>\n </li>\n <br>\n <li>\n <a\n href=\"http://vuejs-templates.github.io/webpack/\"\n target=\"_blank\"\n >\n Docs for This Template\n </a>\n </li>\n </ul>\n <h2>Ecosystem</h2>\n <ul>\n <li>\n <a\n href=\"http://router.vuejs.org/\"\n target=\"_blank\"\n >\n vue-router\n </a>\n </li>\n <li>\n <a\n href=\"http://vuex.vuejs.org/\"\n target=\"_blank\"\n >\n vuex\n </a>\n </li>\n <li>\n <a\n href=\"http://vue-loader.vuejs.org/\"\n target=\"_blank\"\n >\n vue-loader\n </a>\n </li>\n <li>\n <a\n href=\"https://github.com/vuejs/awesome-vue\"\n target=\"_blank\"\n >\n awesome-vue\n </a>\n </li>\n </ul>\n </div>\n</template>\n\n<script>\nexport default {\n name: \"HelloWorld\",\n data() {\n return {\n msg: \"Welcome to Your Vue.js App\"\n };\n }\n};\n</script>\n\n<!-- Add \"scoped\" attribute to limit CSS to this component only -->\n<style scoped>\nh1,\nh2 {\n font-weight: normal;\n}\nul {\n list-style-type: none;\n padding: 0;\n}\nli {\n display: inline-block;\n margin: 0 10px;\n}\na {\n color: #42b983;\n}\n</style>\n"
		}
	],
	"like_count":0,
	"id":"vue",
	"git":null,
	"forked_from_sandbox":null,
	"fork_count":0,
	"external_resources":[
	],
	"entry":"index.js",
	"directories":[
		{
		"title":"assets",
		"source_id":"vue",
		"shortid":"0pn4G",
		"id":"0pn4G",
		"directory_shortid":"VvnjX"
		},
		{
		"title":"src",
		"source_id":"vue",
		"shortid":"VvnjX",
		"id":"VvnjX",
		"directory_shortid":null
		},
		{
		"title":"static",
		"source_id":"vue",
		"shortid":"ANqNP",
		"id":"ANqNP",
		"directory_shortid":null
		},
		{
		"title":"components",
		"source_id":"vue",
		"shortid":"JEP5J",
		"id":"JEP5J",
		"directory_shortid":"VvnjX"
		}
	],
	"description":null,
	"author":null
})

const angular_template = () => ({
	"view_count":0,
	"version":1,
	"user_liked":false,
	"updated_at":"2018-02-07T13:56:17.368167",
	"title":"Angular",
	"template":"angular-cli",
	"tags":[
		"angular"
	],
	"source_id":"angular",
	"privacy":0,
	"owned":false,
	"original_git_commit_sha":null,
	"original_git":null,
	"npm_dependencies":{
		"react-dom":"16.0.0",
		"react":"16.0.0"
	},
	"modules":[
		{
		"title":"environment.prod.ts",
		"source_id":"angular",
		"shortid":"oA1B",
		"is_binary":false,
		"id":"oA1B",
		"directory_shortid":"rBqgk",
		"code":"export const environment = {\n production: true\n};\n"
		},
		{
		"title":"app.module.ts",
		"source_id":"angular",
		"shortid":"nr2J7",
		"is_binary":false,
		"id":"nr2J7",
		"directory_shortid":"ZD1r8",
		"code":"import { BrowserModule } from \"@angular/platform-browser\";\nimport { NgModule } from \"@angular/core\";\n\nimport { AppComponent } from \"./app.component\";\n\n@NgModule({\n declarations: [AppComponent],\n imports: [BrowserModule],\n providers: [],\n bootstrap: [AppComponent]\n})\nexport class AppModule {}\n"
		},
		{
		"title":"app.component.ts",
		"source_id":"angular",
		"shortid":"3Ezxp",
		"is_binary":false,
		"id":"3Ezxp",
		"directory_shortid":"ZD1r8",
		"code":"import { Component } from \"@angular/core\";\n\n@Component({\n selector: \"app-root\",\n templateUrl: \"./app.component.html\",\n styleUrls: [\"./app.component.css\"]\n})\nexport class AppComponent {\n title = \"CodeSandbox\";\n}\n"
		},
		{
		"title":"main.ts",
		"source_id":"angular",
		"shortid":"pRLvQ",
		"is_binary":false,
		"id":"pRLvQ",
		"directory_shortid":"nZnZ5",
		"code":"import { enableProdMode } from \"@angular/core\";\nimport { platformBrowserDynamic } from \"@angular/platform-browser-dynamic\";\n\nimport { AppModule } from \"./app/app.module\";\nimport { environment } from \"./environments/environment\";\n\nif (environment.production) {\n enableProdMode();\n}\n\nplatformBrowserDynamic()\n .bootstrapModule(AppModule)\n .catch(err => console.log(err));\n"
		},
		{
		"title":"styles.css",
		"source_id":"angular",
		"shortid":"Q7YP7",
		"is_binary":false,
		"id":"Q7YP7",
		"directory_shortid":"nZnZ5",
		"code":"/* You can add global styles to this file, and also import other style files */\n\nhtml,\nbody {\n font-family: sans-serif;\n}\n"
		},
		{
		"title":"typings.d.ts",
		"source_id":"angular",
		"shortid":"PEA1W",
		"is_binary":false,
		"id":"PEA1W",
		"directory_shortid":"nZnZ5",
		"code":"/* SystemJS module definition */\ndeclare var module: NodeModule;\ninterface NodeModule {\n id: string;\n}\n"
		},
		{
		"title":"polyfills.ts",
		"source_id":"angular",
		"shortid":"G9ovr",
		"is_binary":false,
		"id":"G9ovr",
		"directory_shortid":"nZnZ5",
		"code":"/**\n * This file includes polyfills needed by Angular and is loaded before the app.\n * You can add your own extra polyfills to this file.\n *\n * This file is divided into 2 sections:\n * 1. Browser polyfills. These are applied before loading ZoneJS and are sorted by browsers.\n * 2. Application imports. Files imported after ZoneJS that should be loaded before your main\n * file.\n *\n * The current setup is for so-called \"evergreen\" browsers; the last versions of browsers that\n * automatically update themselves. This includes Safari >= 10, Chrome >= 55 (including Opera),\n * Edge >= 13 on the desktop, and iOS 10 and Chrome on mobile.\n *\n * Learn more in https://angular.io/docs/ts/latest/guide/browser-support.html\n */\n\n/***************************************************************************************************\n * BROWSER POLYFILLS\n */\n\n/** IE9, IE10 and IE11 requires all of the following polyfills. **/\n// import 'core-js/es6/symbol';\n// import 'core-js/es6/object';\n// import 'core-js/es6/function';\n// import 'core-js/es6/parse-int';\n// import 'core-js/es6/parse-float';\n// import 'core-js/es6/number';\n// import 'core-js/es6/math';\n// import 'core-js/es6/string';\n// import 'core-js/es6/date';\n// import 'core-js/es6/array';\n// import 'core-js/es6/regexp';\n// import 'core-js/es6/map';\n// import 'core-js/es6/weak-map';\n// import 'core-js/es6/set';\n\n/** IE10 and IE11 requires the following for NgClass support on SVG elements */\n// import 'classlist.js'; // Run `npm install --save classlist.js`.\n\n/** IE10 and IE11 requires the following for the Reflect API. */\n// import 'core-js/es6/reflect';\n\n/** Evergreen browsers require these. **/\n// Used for reflect-metadata in JIT. If you use AOT (and only Angular decorators), you can remove.\nimport \"core-js/es7/reflect\";\n\n/**\n * Required to support Web Animations `@angular/platform-browser/animations`.\n * Needed for: All but Chrome, Firefox and Opera. http://caniuse.com/#feat=web-animation\n **/\n// import 'web-animations-js'; // Run `npm install --save web-animations-js`.\n\n/***************************************************************************************************\n * Zone JS is required by default for Angular itself.\n */\nimport \"zone.js/dist/zone\"; // Included with Angular CLI.\n\n/***************************************************************************************************\n * APPLICATION IMPORTS\n */\n"
		},
		{
		"title":"index.html",
		"source_id":"angular",
		"shortid":"mY0jG",
		"is_binary":false,
		"id":"mY0jG",
		"directory_shortid":"nZnZ5",
		"code":"<!doctype html>\n<html lang=\"en\">\n\n<head>\n\t<meta charset=\"utf-8\">\n\t<title>Angular</title>\n\t<base href=\"/\">\n\n\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n\t<link rel=\"icon\" type=\"image/x-icon\" href=\"favicon.ico\">\n</head>\n\n<body>\n\t<app-root></app-root>\n</body>\n\n</html>"
		},
		{
		"title":"app.component.css",
		"source_id":"angular",
		"shortid":"E01p4",
		"is_binary":false,
		"id":"E01p4",
		"directory_shortid":"ZD1r8",
		"code":"ul {\n text-align: center;\n}\n"
		},
		{
		"title":".angular-cli.json",
		"source_id":"angular",
		"shortid":"nxRnD",
		"is_binary":false,
		"id":"nxRnD",
		"directory_shortid":null,
		"code":"{\n \"apps\": [\n {\n \"root\": \"src\",\n \"outDir\": \"dist\",\n \"assets\": [\"assets\", \"favicon.ico\"],\n \"index\": \"index.html\",\n \"main\": \"main.ts\",\n \"polyfills\": \"polyfills.ts\",\n \"prefix\": \"app\",\n \"styles\": [\"styles.css\"],\n \"scripts\": [],\n \"environmentSource\": \"environments/environment.ts\",\n \"environments\": {\n \"dev\": \"environments/environment.ts\",\n \"prod\": \"environments/environment.prod.ts\"\n }\n }\n ]\n}\n"
		},
		{
		"title":"environment.ts",
		"source_id":"angular",
		"shortid":"O6V7L",
		"is_binary":false,
		"id":"O6V7L",
		"directory_shortid":"rBqgk",
		"code":"// The file contents for the current environment will overwrite these during build.\n// The build system defaults to the dev environment which uses `environment.ts`, but if you do\n// `ng build --env=prod` then `environment.prod.ts` will be used instead.\n// The list of which env maps to which file can be found in `.angular-cli.json`.\n\nexport const environment = {\n production: false\n};\n"
		},
		{
		"title":"package.json",
		"source_id":"angular",
		"shortid":"9A214",
		"is_binary":false,
		"id":"9A214",
		"directory_shortid":null,
		"code":"{\n \"name\": \"Angular\",\n \"version\": \"0.0.0\",\n \"license\": \"MIT\",\n \"scripts\": {\n \"ng\": \"ng\",\n \"start\": \"ng serve\",\n \"build\": \"ng build --prod\",\n \"test\": \"ng test\",\n \"lint\": \"ng lint\",\n \"e2e\": \"ng e2e\"\n },\n \"private\": true,\n \"dependencies\": {\n \"@angular/animations\": \"^5.2.0\",\n \"@angular/common\": \"^5.2.0\",\n \"@angular/compiler\": \"^5.2.0\",\n \"@angular/core\": \"^5.2.0\",\n \"@angular/forms\": \"^5.2.0\",\n \"@angular/http\": \"^5.2.0\",\n \"@angular/platform-browser\": \"^5.2.0\",\n \"@angular/platform-browser-dynamic\": \"^5.2.0\",\n \"@angular/router\": \"^5.2.0\",\n \"core-js\": \"^2.4.1\",\n \"rxjs\": \"^5.5.6\",\n \"zone.js\": \"^0.8.19\"\n },\n \"devDependencies\": {\n \"@angular/cli\": \"1.6.6\",\n \"@angular/compiler-cli\": \"^5.2.0\",\n \"@angular/language-service\": \"^5.2.0\",\n \"@types/core-js\": \"0.9.46\",\n \"@types/jasmine\": \"~2.8.3\",\n \"@types/jasminewd2\": \"~2.0.2\",\n \"@types/node\": \"~6.0.60\",\n \"codelyzer\": \"^4.0.1\",\n \"jasmine-core\": \"~2.8.0\",\n \"jasmine-spec-reporter\": \"~4.2.1\",\n \"karma\": \"~2.0.0\",\n \"karma-chrome-launcher\": \"~2.2.0\",\n \"karma-coverage-istanbul-reporter\": \"^1.2.1\",\n \"karma-jasmine\": \"~1.1.0\",\n \"karma-jasmine-html-reporter\": \"^0.2.2\",\n \"protractor\": \"~5.1.2\",\n \"ts-node\": \"~4.1.0\",\n \"tslint\": \"~5.9.1\",\n \"typescript\": \"~2.5.3\"\n },\n \"keywords\": [\"angular\"],\n \"description\": \"\"\n}\n"
		},
		{
		"title":"app.component.html",
		"source_id":"angular",
		"shortid":"2xVGK",
		"is_binary":false,
		"id":"2xVGK",
		"directory_shortid":"ZD1r8",
		"code":"<!--The content below is only a placeholder and can be replaced.-->\n<div style=\"text-align:center\">\n\t<h1>\n\t\tWelcome to {{ title }}!\n\t</h1>\n\t<img width=\"300\" alt=\"Angular Logo\" src=\"data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAyNTAgMjUwIj4KICAgIDxwYXRoIGZpbGw9IiNERDAwMzEiIGQ9Ik0xMjUgMzBMMzEuOSA2My4ybDE0LjIgMTIzLjFMMTI1IDIzMGw3OC45LTQzLjcgMTQuMi0xMjMuMXoiIC8+CiAgICA8cGF0aCBmaWxsPSIjQzMwMDJGIiBkPSJNMTI1IDMwdjIyLjItLjFWMjMwbDc4LjktNDMuNyAxNC4yLTEyMy4xTDEyNSAzMHoiIC8+CiAgICA8cGF0aCAgZmlsbD0iI0ZGRkZGRiIgZD0iTTEyNSA1Mi4xTDY2LjggMTgyLjZoMjEuN2wxMS43LTI5LjJoNDkuNGwxMS43IDI5LjJIMTgzTDEyNSA1Mi4xem0xNyA4My4zaC0zNGwxNy00MC45IDE3IDQwLjl6IiAvPgogIDwvc3ZnPg==\">\n</div>\n"
		}
	],
	"like_count":0,
	"id":"angular",
	"git":null,
	"forked_from_sandbox":null,
	"fork_count":0,
	"external_resources":[
	],
	"entry":"src/main.ts",
	"directories":[
		{
		"title":"app",
		"source_id":"angular",
		"shortid":"ZD1r8",
		"id":"ZD1r8",
		"directory_shortid":"nZnZ5"
		},
		{
		"title":"assets",
		"source_id":"angular",
		"shortid":"g2Dmr",
		"id":"g2Dmr",
		"directory_shortid":"nZnZ5"
		},
		{
		"title":"src",
		"source_id":"angular",
		"shortid":"nZnZ5",
		"id":"nZnZ5",
		"directory_shortid":null
		},
		{
		"title":"environments",
		"source_id":"angular",
		"shortid":"rBqgk",
		"id":"rBqgk",
		"directory_shortid":"nZnZ5"
		}
	],
	"description":null,
	"author":null
})

const preact_template = () => ({
	"view_count":0,
	"version":1,
	"user_liked":false,
	"updated_at":"2017-12-23T17:55:11.765857",
	"title":null,
	"template":"preact-cli",
	"tags":[
	],
	"source_id":"preact",
	"privacy":0,
	"owned":false,
	"original_git_commit_sha":null,
	"original_git":null,
	"npm_dependencies":{
		"preact-compat":"3.17.0",
		"preact":"8.2.5"
	},
	"modules":[
		{
		"title":"index.scss",
		"source_id":"preact",
		"shortid":"xz4Yl",
		"is_binary":false,
		"id":"xz4Yl",
		"directory_shortid":"535A8",
		"code":"html, body {\n\tfont: 14px/1.21 'Helvetica Neue', arial, sans-serif;\n\tfont-weight: 400;\n\tcolor: #444;\n\t-webkit-font-smoothing: antialiased;\n\t-moz-osx-font-smoothing: grayscale;\n}\n\nh1 {\n\ttext-align: center;\n}\n\n.result {\n\tpadding: 10px;\n\tmargin: 10px;\n\tbackground: white;\n\tbox-shadow: 0 1px 5px rgba(0,0,0,0.5);\n}\n"
		},
		{
		"title":"index.js",
		"source_id":"preact",
		"shortid":"wRo98",
		"is_binary":false,
		"id":"wRo98",
		"directory_shortid":null,
		"code":"import \"./style\";\nimport { Component, render } from \"preact\";\nimport { Result } from \"./result\";\n\nconst SEARCH = \"//api.github.com/search/repositories\";\n\nexport default class App extends Component {\n componentDidMount() {\n fetch(`${SEARCH}?q=preact`)\n .then(r => r.json())\n .then(json => {\n this.setState({\n results: (json && json.items) || []\n });\n });\n }\n\n render(props, { results = [] }) {\n return (\n <div>\n <h1>Example</h1>\n <div class=\"list\">\n {results.map(result => <Result result={result} />)}\n </div>\n </div>\n );\n }\n}\n\nif (typeof window !== \"undefined\") {\n render(<App />, document.getElementById(\"root\"));\n}\n"
		},
		{
		"title":"result.js",
		"source_id":"preact",
		"shortid":"poknr",
		"is_binary":false,
		"id":"poknr",
		"directory_shortid":null,
		"code":"export const Result = ({ result }) => {\n return (\n <div class=\"result\">\n <div>\n <a href={result.html_url} target=\"_blank\">\n {result.full_name}\n </a>\n 🌟<strong>{result.stargazers_count}</strong>\n </div>\n <p>\n {result.description}\n </p>\n </div>\n );\n};\n"
		}
	],
	"like_count":0,
	"id":"preact",
	"git":null,
	"forked_from_sandbox":null,
	"fork_count":0,
	"external_resources":[
	],
	"entry":"index.js",
	"directories":[
		{
		"title":"style",
		"source_id":"preact",
		"shortid":"535A8",
		"id":"535A8",
		"directory_shortid":null
		}
	],
	"description":null,
	"author":null
})

const svelte_template = () => ({
	"view_count":0,
	"version":1,
	"user_liked":false,
	"updated_at":"2017-12-23T17:57:46.160014",
	"title":null,
	"template":"svelte",
	"tags":[
	],
	"source_id":"svelte",
	"privacy":0,
	"owned":false,
	"original_git_commit_sha":null,
	"original_git":null,
	"npm_dependencies":{
	},
	"modules":[
		{
		"title":"HelloWorld.html",
		"source_id":"svelte",
		"shortid":"wR48r",
		"is_binary":false,
		"id":"wR48r",
		"directory_shortid":null,
		"code":"<div class=\"container\">\n\t<h1>Hello {{name}}!</h1>\n\n\t<EditingMessage></EditingMessage>\n</div>\n\n<style>\n\t.container {\n\t\ttext-align: center;\n\t\tmargin-top: 2rem;\n\n\t\tfont-family: sans-serif;\n\t}\n</style>\n\n<script>\n\timport EditingMessage from './EditingMessage.html';\n\n\texport default {\n\t\tcomponents: { EditingMessage }\n\t}\n</script>\n"
		},
		{
		"title":"index.js",
		"source_id":"svelte",
		"shortid":"wRo98",
		"is_binary":false,
		"id":"wRo98",
		"directory_shortid":null,
		"code":"import HelloWorld from \"./HelloWorld.html\";\n\nconst app = new HelloWorld({\n target: document.getElementById(\"root\"),\n data: {\n name: \"Svelte\"\n }\n});\n"
		},
		{
		"title":"EditingMessage.html",
		"source_id":"svelte",
		"shortid":"LRkL4",
		"is_binary":false,
		"id":"LRkL4",
		"directory_shortid":null,
		"code":"<h2>Start editing to see some magic happen.</h2>"
		}
	],
	"like_count":0,
	"id":"svelte",
	"git":null,
	"forked_from_sandbox":null,
	"fork_count":0,
	"external_resources":[
	],
	"entry":"index.js",
	"directories":[
	],
	"description":null,
	"author":null
})

module.exports = {
	vanilla_template,
	vue_template,
	create_react_app_template,
	angular_template,
	svelte_template,
	preact_template,
}